import AddTask from "@/components/AddTask";
import Header from "@/components/Header";
import Info from "@/components/Info";
import Task from "@/components/Task";
import { allTasks, myTheme, singleTask } from "@/redux/selector";
import Head from "next/head";
import { useSelector } from "react-redux";

export default function Home() {
  const allTask = useSelector(allTasks);

  const myTask = useSelector(singleTask);

  const theme = useSelector(myTheme);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`main-page__container ${theme}`}>
        <div className="main-page__content">
          <div className="main-page__tasks">
            {allTask.map((task) => (
              <Task key={task?.id} task={task} />
            ))}
          </div>
          {myTask && (
            <div className="main-page__info">
              <Info />
            </div>
          )}
        </div>
        <AddTask />
      </main>
    </>
  );
}
